baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme= "PaperMod"
sectionPagesMenu = 'main'
enableEmoji = true

[params]
comments = true

[services]
  [services.disqus]
    shortname = 'edar-1'

